---
- name: Start docker consul container
  community.docker.docker_compose:
    state: present
    project_name: patroni_cluster
    definition:
      version: '2'
      services:
        consul:
          image: "{{ consul_image }}:{{ consul_image_version }}"
          container_name: "{{ consul_container_name }}"
          ports: "{{ consul_expose_ports }}"
          environment:
            TZ: "{{ cluster_timezone }}"
          hostname: "{{ consul_host }}"
          restart: always
          labels: "{{ consul_docker_labels }}"
          command: "agent -server -advertise {{ cluster_host_ip }} -bootstrap-expect 3 -client 0.0.0.0  -retry-join {{ cluster_peer1_ip }} -retry-join {{ cluster_peer2_ip }}"
